//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.21 at 05:29:54 PM PST 
//

package com.walmartlabs.testdemo.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.walmartlabs.testdemo.model package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _Dog_QNAME = new QName(
			"http://www.example.org/requestOne/", "dog");
	private final static QName _Cat_QNAME = new QName(
			"http://www.example.org/requestTwo/", "dog");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: com.walmartlabs.testdemo.model
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Dog }
	 * 
	 */
	public Animal createDog() {
		return new Dog();
	}

	public Animal createCat() {
		return new Cat();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Dog }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.example.org/requestOne/", name = "dog")
	public JAXBElement<Dog> createDog(Dog value) {
		return new JAXBElement<Dog>(_Dog_QNAME, Dog.class, null, value);
	}

	@XmlElementDecl(namespace = "http://www.example.org/requestTwo/", name = "cat")
	public JAXBElement<Cat> createCat(Cat value) {
		return new JAXBElement<Cat>(_Cat_QNAME, Cat.class, null, value);
	}

}
