//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.21 at 05:29:54 PM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/requestOne/")
package com.walmartlabs.testdemo.model;
